### ISSUE TITLE
Unable to run "meepo serve" on windows x86

### ISSUE THREAD

**Issue by Warkeeper** [PeerXu/meepo#9]
## Environment: 
OS Version: Windows 10 Pro 20H2 (x86)
Meepo Version: meepo_windows_amd64

## What's going on
After extracting meepo_windows_amd64.zip, I successfully run ".\meepo.exe config init id=yb1." Then I run ".\meepo.exe serve", it shows "panic: Unsupported daemon on windows" no matter if I run it with or without administration permission.

## Detail error stack
```
PS C:\software\meepo> .\meepo.exe serve
panic: Unsupported daemon on windows

goroutine 1 [running]:
github.com/PeerXu/meepo/pkg/util/daemon.Daemon(...)
        github.com/PeerXu/meepo/pkg/util/daemon/daemon_windows.go:8
github.com/PeerXu/meepo/cmd.meepoSummon(0x1c3dbc0, 0x1c90760, 0x0, 0x0, 0x0, 0x0)
        github.com/PeerXu/meepo/cmd/serve.go:73 +0x1687
github.com/spf13/cobra.(*Command).execute(0x1c3dbc0, 0x1c90760, 0x0, 0x0, 0x1c3dbc0, 0x1c90760)
        github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x1c3d920, 0xad670b, 0xc000086058, 0xaeba01)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
github.com/PeerXu/meepo/cmd.Execute()
        github.com/PeerXu/meepo/cmd/root.go:17 +0x34
main.main()
        github.com/PeerXu/meepo/main.go:6 +0x27
```

**Comment by Warkeeper** [comment]
windows 10 doesn't support daemon feature for now, set command parameter "daemon" to false could solve the problem.
```
.\meepo.exe serve --daemon=false
```
